name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: https://rustwasm.github.io/wasm-pack/installer/init.sh && npm install
    - name: Run tests
      run: npm test
